# Site
name: "GodotAwesome"
title: "GodotAwesome"
description: "Your ultimate hub for Godot Engine excellence. Discover game showcases, tutorials, trending topics, and resources for indie developers. Explore the power of open-source game development with curated content, inspiring projects, and community-driven insights."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'G-BH9P4LY6E7'
disqus: 'betaversion'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  alihan98ersoy:
    name: Alihan
    display_name: alihan98ersoy
    avatar: 'assets/images/alihan.jpg'
    gravatar: 'assets/images/alihan.jpg'
    email: alihan98ersoy@gmail.com
    web: https://alihan98ersoy.com.tr
    twitter: https://x.com/alihan98ersoy
    description: "Author of GodotAwesome, a Godot game engine blog."
  godotscribe:
    name: GodotScribe 
    display_name: GodotScribe
    avatar: 'assets/images/godotscribe.png'
    gravatar: 'assets/images/godotscribe.png'
    email: 
    web: 
    twitter: 
    description: "Author of GodotAwesome. She is creating valuable, reader-friendly content for the GodotAwesome community!."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
